/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Controlador.PersonaControlador;
import Controlador.RegistrosControlador;
import Modelo.DirrecionModelo;
import Modelo.PersonaModelo;
import Modelo.RegistrosModelo;

/**
 *
 * @author Usuario
 */
public class Registros extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registros
     */
    public Registros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_apellido = new javax.swing.JTextField();
        lbl_grupoprio1 = new javax.swing.JLabel();
        lbl_edad1 = new javax.swing.JLabel();
        cmb_grupoPrio = new javax.swing.JComboBox<>();
        txt_edad = new javax.swing.JTextField();
        cmb_valoracion = new javax.swing.JComboBox<>();
        lbl_motivo1 = new javax.swing.JLabel();
        txt_celular = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        lbl_nombre2 = new javax.swing.JLabel();
        lbl_valoracion1 = new javax.swing.JLabel();
        txt_motivo = new javax.swing.JTextField();
        lbl_telefono1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        lbl_celular1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_nombre3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_referencia = new javax.swing.JTextField();
        txt_barrio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_callePrin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_calleSecu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Persona"));

        lbl_grupoprio1.setText("Grupo Prioritario:");

        lbl_edad1.setText("Edad:");

        cmb_grupoPrio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adulto Mayor", "Capacidades Especiales", "Convenio LPSA", "Mujeres Embarazadas", "Niños y Adolescentes", "PEA" }));

        cmb_valoracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leve", "Moderada", "Grave" }));
        cmb_valoracion.setToolTipText("");
        cmb_valoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_valoracionActionPerformed(evt);
            }
        });

        lbl_motivo1.setText("Motivo:");

        lbl_nombre2.setText("Apellido:");

        lbl_valoracion1.setText("Valoracion:");

        lbl_telefono1.setText("Teléfono:");

        jLabel3.setText("Cedula: ");

        txt_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyTyped(evt);
            }
        });

        lbl_celular1.setText("Celular:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Registros");

        lbl_nombre3.setText("Nombre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_valoracion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_valoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_nombre3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(89, 89, 89)
                        .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre2)
                            .addComponent(lbl_telefono1)
                            .addComponent(lbl_grupoprio1)
                            .addComponent(lbl_motivo1)
                            .addComponent(lbl_edad1)
                            .addComponent(lbl_celular1))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_grupoPrio, 0, 163, Short.MAX_VALUE)
                            .addComponent(txt_telefono)
                            .addComponent(txt_apellido)
                            .addComponent(txt_motivo)
                            .addComponent(txt_edad)
                            .addComponent(txt_celular))))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(160, 160, 160))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre3)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre2)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefono1)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_grupoprio1)
                    .addComponent(cmb_grupoPrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_motivo1)
                    .addComponent(txt_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_edad1)
                    .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_celular1)
                    .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_valoracion1)
                    .addComponent(cmb_valoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección"));

        jLabel2.setText("Barrio:");

        jLabel5.setText("Calle Principal:");

        jLabel6.setText("Calle Secundaria:");

        jLabel7.setText("Punto Referencia:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_callePrin)
                    .addComponent(txt_calleSecu)
                    .addComponent(txt_referencia)
                    .addComponent(txt_barrio, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_callePrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_calleSecu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_referencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_registrar.setText("registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_buscar)
                            .addComponent(btn_registrar)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btn_buscar)
                        .addGap(31, 31, 31)
                        .addComponent(btn_registrar)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_valoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_valoracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_valoracionActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        String grupo = (String) cmb_grupoPrio.getSelectedItem();
        String valoracion = (String) cmb_valoracion.getSelectedItem();
        String nombre = txt_nombre.getText();
        String apellido = txt_apellido.getText();

        String motivo = txt_motivo.getText();
        String estado = "Pendiente"; 
        int numeroTurno = 8; // Aquí ingresa el número de turno que desees

        if (!nombre.isEmpty()) {
            nombre = Character.toUpperCase(nombre.charAt(0)) + nombre.substring(1).toLowerCase();
        }

        if (!apellido.isEmpty()) {
            apellido = Character.toUpperCase(apellido.charAt(0)) + apellido.substring(1).toLowerCase();
        }

        String idRol;
        if ("Adulto Mayor".equals(grupo)) {
            idRol = "Adulto Mayor";
        } else if ("Capacidades Especiales".equals(grupo)) {
            idRol = "Capacidades Especiales";
        } else if ("Convenio LPSA".equals(grupo)) {
            idRol = "Convenio LPSA";
        } else if ("Mujeres Embarazadas".equals(grupo)) {
            idRol = "Mujeres Embarazadas";
        } else if ("Niños y Adolescentes".equals(grupo)) {
            idRol = "Niños y Adolescentes";
        } else if ("PEA".equals(grupo)) {
            idRol = "PEA";
        } else {
            idRol = "";
        }
        
        String Rol; 

        if ("Leve".equals(valoracion)) {
            Rol = "Leve";
        } else if ("Moderada".equals(valoracion)) {
            Rol = "Moderada";
        } else if ("Grave".equals(valoracion)) {
            Rol = "Grave";
        } else {
            Rol = "";
        }
        
        PersonaModelo p = new PersonaModelo(Integer.parseInt(txt_cedula.getText()), txt_nombre.getText(), txt_apellido.getText(),
                Integer.parseInt(txt_edad.getText()), idRol, Integer.parseInt(txt_telefono.getText()), Integer.parseInt(txt_celular.getText()),
                0);

        DirrecionModelo d = new DirrecionModelo();
        d.setCALLE_PRINCIPAL(txt_callePrin.getText());
        d.setCALLE_SECUNDARIA(txt_calleSecu.getText());
        d.setBARRIO(txt_barrio.getText());
        d.setPUNTO_REFERENCIA(txt_referencia.getText());

        PersonaControlador u = new PersonaControlador();
        u.crearPersona(p, d);
        
        
        RegistrosModelo r = new RegistrosModelo(0, motivo,Rol, estado, numeroTurno);
        RegistrosControlador rc = new RegistrosControlador();
        rc.IngresarRegistros(r);

    }//GEN-LAST:event_btn_registrarActionPerformed

    private void txt_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') || (txt_cedula.getText().length() >= 10)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_cedulaKeyTyped

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        PersonaModelo pm = new PersonaModelo();
        RegistrosControlador c = new RegistrosControlador();
        c.PersonaExistente(pm);
    }//GEN-LAST:event_btn_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JComboBox<String> cmb_grupoPrio;
    private javax.swing.JComboBox<String> cmb_valoracion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_celular1;
    private javax.swing.JLabel lbl_edad1;
    private javax.swing.JLabel lbl_grupoprio1;
    private javax.swing.JLabel lbl_motivo1;
    private javax.swing.JLabel lbl_nombre2;
    private javax.swing.JLabel lbl_nombre3;
    private javax.swing.JLabel lbl_telefono1;
    private javax.swing.JLabel lbl_valoracion1;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_barrio;
    private javax.swing.JTextField txt_callePrin;
    private javax.swing.JTextField txt_calleSecu;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_celular;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_motivo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_referencia;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
